### ISSUE TITLE
WonderTANG 1.02d board compatibility

### ISSUE THREAD

**Issue by herraa1** [buppu3/tnCart#10]
First, thanks for your awesome project and for making it public so we all can learn from you.

I noticed that your tnCart board is using (mostly) the same tn20k signal mapping as the WonderTANG 1.02d.
The only difference is that the WonderTANG MSEL0_33 signal is mapped to tnCart MSEL1_33 and WonderTANG MSEL1_33 is mapped to tnCart MSEL0_33. Other than that the two board designs are "equivalent".

I made a small modification to the tnCart RTL to accomodate the difference with the WonderTANG and tested that the FPGA code works nicely too on the WonderTANG 1.02d.
Making it work with the WonderTANG 2.0b required a few more changes because the signal mapping is slightly different and the audio signal is sent to the internal tn20k dac using I2S, but I also did a quick (really dirty) test and it works too.

This was discussed at [msx.org](https://www.msx.org/forum/msx-talk/hardware/wondertang-who-wants-to-juice-up-your-msx?page=44) .

I was wondering if you are interested in making your tnCart FPGA RTL compatible with the WonderTANG 1.02d and what would be your preference in achieving that:
- One option could be changing your tnCart board design to make MSEL0_33 select A0-A7 and MSEL1_33 select A8-A15 as in the WonderTANG, that would make your RTL directly useable on the WonderTANG 1.02d and the tnCart.
- Another option would be to have a config option to select between the two boards at bitstream build time and generate different bitstreams for each of them. This option could be used too for making the tnCart FPGA code compatible with the WonderTANG 2.0 (probably with a different project to select different constraint files for both the physical constraints .sdc due to the different IO mapping and maybe timing constraints .cst to account for the new CLK signal for the I2S transmitter to the tn20k internal DAC).

Regarding audio, I think that the WonderTANG 1.02d audio (using the fpga 1-bit DAC) is cleaner (less plagued with noise and interference) than the WonderTANG 2.0b audio (using the tn20k DAC, which amplifies even more the noises). This happens both with the WonderTANG fpga code and your (modified) tnCart fpga code.
So I'm not sure if it is worth investing time in the WonderTANG 2.0, unless there is a way to make the audio cleaner.

What do you think about the tnCart FPGA compatibility with the existing WonderTANG boards?

Thanks!

**Comment by buppu3** [comment]
Thank you for your interest in tnCart.

I have concerns with the current tnCart circuit and I will be modifying the circuit in the near future. After this modification, tnCart and WonderTANG will no longer be pin compatible.

So, in order to maintain compatibility between the different boards, I think it would be best to create a project with a modified .sdc for each board and synthesize a bitstream for each.

**Comment by herraa1** [comment]
Thanks for your comments.

Would you prefer the WonderTANG compatibility changes handled by others in an external fork of you repository (so that you can focus just on tnCart)? Or would you accept pull requests for WonderTANG boards in your repo?

Thanks again.

**Comment by buppu3** [comment]
I can't confirm WonderTANG V2.0 compatible works, so I can't respond quickly to pull requests.
Considering this, I think it is better to handle the forked code in your repository.

Please take it in consideration.

**Comment by herraa1** [comment]
Sure, that makes sense.
I'll handle those modifications in a separate fork.

Thanks a lot again.

**Comment by herraa1** [comment]
Just for you reference, the mentioned fork is available at [https://github.com/herraa1/tnCartWonder](https://github.com/herraa1/tnCartWonder).

I'm closing the issue.

Thank you.

**Comment by DFL1973** [comment]
> Just for you reference, the mentioned fork is available at https://github.com/herraa1/tnCartWonder.
> 
> I'm closing the issue.
> 
> Thank you.

How about a bitstream for wondertang v1.01c? Should be almost the same as 1.02d, except for the INT line (inverted?)

**Comment by herraa1** [comment]
> > Just for you reference, the mentioned fork is available at https://github.com/herraa1/tnCartWonder.
> > I'm closing the issue.
> > Thank you.
> 
> How about a bitstream for wondertang v1.01c? Should be almost the same as 1.02d, except for the INT line (inverted?)

I pushed the required changes and a bitstream (without V9990) for V1.01c.

**Comment by taupter** [comment]
It would be nice to have one that works with the WonderTang that Victor
Trucco sold.

Em sáb., 14 de set. de 2024 16:01, herraa1 ***@***.***>
escreveu:

**Comment by herraa1** [comment]
> It would be nice to have one that works with the WonderTang that Victor Trucco sold.

You may need to ask Victor Trucco which version from Luis Antoniosi is equivalent to the one(s) he sold and then try to use the bitstream for that version.

**Comment by vtrucco** [comment]
> > It would be nice to have one that works with the WonderTang that Victor Trucco sold.
> 
> You may need to ask Victor Trucco which version from Luis Antoniosi is equivalent to the one(s) he sold and then try to use the bitstream for that version.

V1.01c.
