### ISSUE TITLE
SofaRun and MGSP do not detect the SCC

### ISSUE THREAD

**Issue by herraa1** [buppu3/tnCart#11]
SofaRun 8.1 (with SofaROM 3.3) does not autodetect the SCC from tnCart. When manually specifying the slot location of the SCC (1-2) SofaRun complains that the SCC and Memory Mapper share the same slot.

MGSP 2.1.3 does not detect the SCC from tnCart (and shows "SCC SLOT #none" when loading). The FM is properly detected.

I don't know if something can be changed in tnCart to fix that, or if the mentioned tools need to be updated to support the tnCart.

Thanks.

**Comment by buppu3** [comment]
I checked the behavior of SofaRun (SofaROM v3.3) on tnCart cartridges

- tnCart(SCC-I) detected successfully
- tnCart (SCC) is not detected; it is detected by setting the External SCC setting to Yes in SofaRun. Also, a warning will be shown.
- "Gekitotsu pennant race"(Real SCC cartridge) is not detected; it is detected by setting the External SCC setting to Yes in SofaRun.

The tnCart board detects SCC as well as the real thing, and SCC output in SofaRun seems to be fine.
Furthermore, SCC is also detected in the MGSP.

I think the reason why SCC is not detected by tnCartWonder is the same as #12.

Also, I don't know why SofaRom is displaying the warning. If the primary slots are identical, what is the problem?

**Comment by herraa1** [comment]
I've seen in one of your twitter posts how you manage to make MGSP (and SofaRun) work.
You first load TNCROM with option /N and no ROM, then load the program you want to use with the SCC.

I tested it and it works perfectly (both MGSP and SofaRun).

TNCROM /T KONAMI_SCC_I /N
SR
or
MGSP

So the detection problem is not related to #12, it is simply that the SCC needs to be activated first because it is not active by default (as in the WonderTANG! fpga code for example).

Thanks for your comments.
