### ISSUE TITLE
Problem loading DEMO9990.ROM with TNCROM

### ISSUE THREAD

**Issue by herraa1** [buppu3/tnCart#18]
I made the following test.

I have two WonderTANGs (WTs). I built one tnCartWonder bitstream A with just V9990 and nothing else, and another bitstream B with all except V9990. I flashed WT A with bitstream A and WT B with bitstream B.

I inserted WT A (V9990) in slot 1 and WT B (Nextor, RAM, SCC, FM, SD, ...) in slot 2 of one of my MSX.
I turned on the MSX and it booted correctly, and I tried to load DEMO9990.ROM from [Tiny Yarou](https://www.youtube.com/watch?v=I6kXyMaED0s) with tncrom using:

~~~shell
TNCROM /T KONAMI /R DEMO9990.ROM
~~~

The tncrom tool loaded the rom, rebooted the computer and the rom executed.
But on the welcome screen where you can press [1] or [2] to launch any of the two demos included, when you press [1] or [2] instead of lauching the demos, the welcome screen appears again and again (allowing you to press [1] or [2] but behaving in the same way).

If instead of using tncrom I use SofaRun, the DEMO9990.ROM loads correctly and I can launch the demos without problems by pressing [1] or [2].

I'm using TNCROM 0.0.6.

I tested with the same results both my Omega Home Computer and my Panasonic FSA1-WSX.

I tested too using a FlashJack cartridge instead of the WT B, and loading the DEMO9990.ROM with FROM (the native tool to load ROMs using a FlashJacks) worked correctly too.

So it seems there is still some problem with TNCROM.

**Comment by buppu3** [comment]
What is your intention in using "KONAMI"?
This demo works in "ASCII16K".
TNCROM does not support patching for bank switching like SofaRun does.

**Comment by herraa1** [comment]
Oh, yes, you are completely right, the rom should be loaded with an ASCII 16K rom mapper...

I verified that it works correctly using the `/T ASCII16` option using TNCROM.
And I confirmed that the FROM utility of the Flashjacks reports that it uses an ASCII16K mapper, and SofaRun reports that it is using an ASCII16W mapper.

I suppose I got fooled because the rom loaded (and kind of worked) in the first place without noticing that I was using the wrong mapper.

I guess it is not easy nor reliable to automatically detect which mapper type uses each rom.
For what I've read, some solutions use an external database to determine the mapper type (mapping a rom checksum to a mapper type), others try to guess the mapper type by looking at some signatures or by looking at the potential number of writes the rom does to the mapper address registers like in [openMSX](https://github.com/openMSX/openMSX/blob/master/src/memory/RomFactory.cc#L63).
Maybe the latter could be incorporated into TNCROM to reduce mistakes like mine.

Thanks!

**Comment by buppu3** [comment]
Yes, it would be. It would be useful to have a function to detect it automatically.

It would be sure to refer to a database from hash values like OpenMSX, but it is difficult to create a database for TNCROM from scratch, and it is also difficult to use database references from other software due to licensing reasons.
In this case, although it is not a reliable method, searching for “LD (nnnn),A” while transferring the ROM image file would be more realistic.

**Comment by herraa1** [comment]
Thanks for your comments.
I'm closing this issue, as it is solved/clarified.

I'll play a bit with the autodetection of megarom mappers for tncrom.
